package com.zyh.javaim.logic.dao.mapper;

import com.zyh.javaim.logic.dao.entity.OfflineMessage;
import com.zyh.javaim.logic.dao.entity.OfflineMessageExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface OfflineMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_offline
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_offline
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    int insert(OfflineMessage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_offline
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    int insertSelective(OfflineMessage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_offline
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    List<OfflineMessage> selectByExample(OfflineMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_offline
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    OfflineMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_offline
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    int updateByPrimaryKeySelective(OfflineMessage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_offline
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    int updateByPrimaryKey(OfflineMessage row);
}