package com.zyh.javaim.logic.dao.mapper;

import com.zyh.javaim.logic.dao.entity.Seq;
import com.zyh.javaim.logic.dao.entity.SeqExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_seq
     *
     * @mbg.generated Tue Mar 26 22:04:51 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_seq
     *
     * @mbg.generated Tue Mar 26 22:04:51 CST 2024
     */
    int insert(Seq row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_seq
     *
     * @mbg.generated Tue Mar 26 22:04:51 CST 2024
     */
    int insertSelective(Seq row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_seq
     *
     * @mbg.generated Tue Mar 26 22:04:51 CST 2024
     */
    List<Seq> selectByExample(SeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_seq
     *
     * @mbg.generated Tue Mar 26 22:04:51 CST 2024
     */
    Seq selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_seq
     *
     * @mbg.generated Tue Mar 26 22:04:51 CST 2024
     */
    int updateByExampleSelective(@Param("row") Seq row, @Param("example") SeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_seq
     *
     * @mbg.generated Tue Mar 26 22:04:51 CST 2024
     */
    int updateByExample(@Param("row") Seq row, @Param("example") SeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_seq
     *
     * @mbg.generated Tue Mar 26 22:04:51 CST 2024
     */
    int updateByPrimaryKeySelective(Seq row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_seq
     *
     * @mbg.generated Tue Mar 26 22:04:51 CST 2024
     */
    int updateByPrimaryKey(Seq row);
}