package com.zyh.javaim.logic.dao.entity;

public class Friend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_friend.id
     *
     * @mbg.generated Mon Mar 25 12:17:30 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_friend.user_id
     *
     * @mbg.generated Mon Mar 25 12:17:30 CST 2024
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_friend.friend_id
     *
     * @mbg.generated Mon Mar 25 12:17:30 CST 2024
     */
    private Long friendId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_friend.id
     *
     * @return the value of im_friend.id
     *
     * @mbg.generated Mon Mar 25 12:17:30 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_friend.id
     *
     * @param id the value for im_friend.id
     *
     * @mbg.generated Mon Mar 25 12:17:30 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_friend.user_id
     *
     * @return the value of im_friend.user_id
     *
     * @mbg.generated Mon Mar 25 12:17:30 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_friend.user_id
     *
     * @param userId the value for im_friend.user_id
     *
     * @mbg.generated Mon Mar 25 12:17:30 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_friend.friend_id
     *
     * @return the value of im_friend.friend_id
     *
     * @mbg.generated Mon Mar 25 12:17:30 CST 2024
     */
    public Long getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_friend.friend_id
     *
     * @param friendId the value for im_friend.friend_id
     *
     * @mbg.generated Mon Mar 25 12:17:30 CST 2024
     */
    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }
}