package com.zyh.javaim.logic.dao.entity;

public class OfflineMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_offline.id
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_offline.msg_id
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    private Long msgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_offline.msg_type
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    private Integer msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_offline.content
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_offline.to_user_id
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    private Long toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_offline.has_read
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    private Byte hasRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_offline.id
     *
     * @return the value of im_offline.id
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_offline.id
     *
     * @param id the value for im_offline.id
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_offline.msg_id
     *
     * @return the value of im_offline.msg_id
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public Long getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_offline.msg_id
     *
     * @param msgId the value for im_offline.msg_id
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_offline.msg_type
     *
     * @return the value of im_offline.msg_type
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_offline.msg_type
     *
     * @param msgType the value for im_offline.msg_type
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_offline.content
     *
     * @return the value of im_offline.content
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_offline.content
     *
     * @param content the value for im_offline.content
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_offline.to_user_id
     *
     * @return the value of im_offline.to_user_id
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public Long getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_offline.to_user_id
     *
     * @param toUserId the value for im_offline.to_user_id
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public void setToUserId(Long toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_offline.has_read
     *
     * @return the value of im_offline.has_read
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public Byte getHasRead() {
        return hasRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_offline.has_read
     *
     * @param hasRead the value for im_offline.has_read
     *
     * @mbg.generated Tue Mar 26 17:35:54 CST 2024
     */
    public void setHasRead(Byte hasRead) {
        this.hasRead = hasRead;
    }
}