package com.zyh.javaim.logic.dao.entity;


public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_users.id
     *
     * @mbg.generated Tue Mar 19 12:36:45 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_users.user_name
     *
     * @mbg.generated Tue Mar 19 12:36:45 CST 2024
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_users.password
     *
     * @mbg.generated Tue Mar 19 12:36:45 CST 2024
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_users.id
     *
     * @return the value of proj_users.id
     *
     * @mbg.generated Tue Mar 19 12:36:45 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_users.id
     *
     * @param id the value for proj_users.id
     *
     * @mbg.generated Tue Mar 19 12:36:45 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_users.user_name
     *
     * @return the value of proj_users.user_name
     *
     * @mbg.generated Tue Mar 19 12:36:45 CST 2024
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_users.user_name
     *
     * @param userName the value for proj_users.user_name
     *
     * @mbg.generated Tue Mar 19 12:36:45 CST 2024
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_users.password
     *
     * @return the value of proj_users.password
     *
     * @mbg.generated Tue Mar 19 12:36:45 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_users.password
     *
     * @param password the value for proj_users.password
     *
     * @mbg.generated Tue Mar 19 12:36:45 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}